#!/bin/bash

function help(){
    echo "NAME"
    echo "    install_pip - install pip requirements."
    echo 
    echo "SYNOPSIS"
    echo "    /bin/bash install_pip [-h]"
    echo "                          [-p requirements_folder_path]"
    echo 
    echo "DESCRIPTION"
    echo "    Sript that installs pip requirements for the module."
    echo "    Useful when other pojects use the module."
    echo "    References:"
    echo "    https://www.atareao.es/tutorial/scripts-en-bash/una-ayuda-para-tus-scripts/"
    echo  
    echo "OPTIONS" 
    echo "    -h, --help"
    echo "        Optional."
    echo "        Show help for this function."
    echo "    -p, --path"
    echo "        Mandatory."
    echo "        Absolute path to the folder where this project has"
    echo "        been downloaded, the name of the project's folder"
    echo "        must be provided at the path."
    echo
    echo "EXAMPLE" 
    echo "    /bin/bash install_pip -p /home/user/requests_custom/"
}

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -p|--path)
	    folder_requirements_path="$2"
	    # Delete argument
            shift
	    # Delete value
            shift
            ;;
        -h|--help)
            help
            exit
            ;;
        *)
            echo "[ERROR] unknown parameter"
            echo
            help
            exit 1
            ;;
    esac
done

# Check path not provided.
if [ -z "$folder_requirements_path" ]
then
    echo "[ERROR] path not provided"
    echo
    help
    exit 1
else
    # Path must end with /
    if [[ $folder_requirements_path != */ ]]
    then
        folder_requirements_path="${folder_requirements_path}/"
    fi
fi


echo "[DEBUG] Init. Install pip requirements."
# Show current path, pwd command result.
echo "[DEBUG] Folder 'requirements' path: "$folder_requirements_path
# Absolute path of the file with pip requirements.
file_requirements="${folder_requirements_path}requirements.txt"
# Show path with requirements.
echo "[DEBUG] File with requirements: "$file_requirements
# Install requirements.
echo "[DEBUG] Init. Install pip requirements"
pip install -r $file_requirements
